Repository PPG007/PPG007.github.io, pull requests merged in 2022-04, with the labels that each got.

#27 openwrt: refine double eth lan setting
  docs/images/openwrt/lanDHCPSetting.png
  docs/openwrt/docs/doubleEth.md
Labels: feature

#28 ubuntu-init: refine docker installation
  docs/ubuntu-20.04-init/docs/docker.md
Labels: refine

#37 kubernetes: add nginx ingress controller
  docs/kubernetes/docs/ingress.md
  docs/kubernetes/index.js
Labels: feature

#40 kubernetes: add secret
  docs/images/kubernetes/secretTypes.png
  docs/kubernetes/docs/secret.md
  docs/kubernetes/index.js
Labels: feature

#41 kubernetes: add storage
  docs/kubernetes/docs/secret.md
  docs/kubernetes/docs/storage.md
  docs/kubernetes/index.js
Labels: Doing, feature

#43 kubernetes: add configMap
  docs/kubernetes/docs/configMap.md
  docs/kubernetes/index.js
Labels: feature

#42 Kubernetes secret
  docs/kubernetes/docs/secret.md
Labels: refine

#45 kubernetes: add job and cronjob
  docs/kubernetes/docs/job.md
  docs/kubernetes/index.js
Labels: feature

#48 kubernetes: add statefulSet
  docs/kubernetes/docs/statefulSet.md
  docs/kubernetes/index.js
Labels: feature

#49 kubernetes: add daemonSet
  docs/kubernetes/docs/daemonSet.md
  docs/kubernetes/index.js
Labels: feature

#25 kubernetes
  docs/.vuepress/config/navbar.js
  docs/.vuepress/config/sidebar.js
  docs/images/kubernetes/components-of-kubernetes.svg
  docs/images/kubernetes/container_evolution.svg
  docs/images/kubernetes/secretTypes.png
  docs/kubernetes/README.md
  docs/kubernetes/docs/basic.md
  docs/kubernetes/docs/component.md
  docs/kubernetes/docs/configMap.md
  docs/kubernetes/docs/daemonSet.md
  docs/kubernetes/docs/deployment.md
  docs/kubernetes/docs/ingress.md
  docs/kubernetes/docs/install.md
  docs/kubernetes/docs/job.md
  docs/kubernetes/docs/kuberesolver.md
  docs/kubernetes/docs/manage.md
  docs/kubernetes/docs/pod.md
  docs/kubernetes/docs/secret.md
  docs/kubernetes/docs/service.md
  docs/kubernetes/docs/statefulSet.md
  docs/kubernetes/docs/storage.md
  docs/kubernetes/index.js
Labels: Doing, feature

#53 config: refine navbar
  docs/.vuepress/config/navbar.js
Labels: refine

#54 Istio
  docs/.vuepress/config/navbar.js
  docs/.vuepress/config/sidebar.js
  docs/images/istio/perNode.png
  docs/images/istio/perNodeAndServiceAccount.png
  docs/images/istio/remoteL7.png
  docs/images/istio/serviceMesh.jpg
  docs/images/istio/sidecar.png
  docs/istio/README.md
  docs/istio/docs/basic.md
  docs/istio/docs/examples.md
  docs/istio/docs/installation.md
  docs/istio/docs/principle.md
  docs/istio/docs/trafficManagement.md
  docs/istio/index.js
Labels: Doing, feature

#58 ubuntu-init: fix jetbrains link
  docs/ubuntu-20.04-init/docs/jetbrains.md
Labels: refine

#60 ubuntu20.04init/nodejs: refine alibaba registry url
  docs/ubuntu-20.04-init/docs/nodejs.md
Labels: refine

#56 openssl
  docs/.vuepress/config/navbar.js
  docs/.vuepress/config/sidebar.js
  docs/openssl/README.md
  docs/openssl/docs/basic.md
  docs/openssl/docs/ca.md
  docs/openssl/docs/commands.md
  docs/openssl/index.js
Labels: Doing, feature

#62 config: refine sidebar json and navbar config
  docs/.vuepress/config.js
  docs/.vuepress/config/bars.js
  docs/.vuepress/config/navbar.js
  docs/.vuepress/config/navbarOrder.json
  docs/.vuepress/config/sidebar.js
  docs/SpringBoot/index.json
  docs/SpringCloud/index.json
  docs/SpringMVC/index.json
  docs/activemq/index.json
  docs/annotation-and-reflection/index.json
  docs/axios/index.json
  docs/clean-code/index.json
  docs/codingstyle/index.json
  docs/css/index.json
  docs/dart/index.json
  docs/design-pattern/index.json
  docs/docker/index.json
  docs/domain/index.json
  docs/dubbo/index.json
  docs/es6/index.json
  docs/gin/index.json
  docs/git/index.json
  docs/go/index.json
  docs/grpc-and-protobuf/index.json
  docs/html/index.json
  docs/istio/index.json
  docs/javaio/index.json
  docs/javaknowledge/index.json
  docs/javanet/index.json
  docs/javascript/index.js
  docs/javascript/index.json
  docs/javathread/index.json
  docs/kubernetes/index.json
  docs/markdown/index.json
  docs/mongodb/index.json
  docs/mybatis/index.json
  docs/netty/index.json
  docs/openssl/index.js
  docs/openssl/index.json
  docs/openwrt/index.json
  docs/redis/index.json
  docs/regex/index.json
  docs/restful/index.json
  docs/spring/index.json
  docs/ubuntu-20.04-init/index.json
  docs/vscode/index.json
  docs/vue2/index.json
  docs/vue3/index.json
  docs/zookeeper/index.json
Labels: refine

#63 README: refine home details
  docs/README.md
Labels: refine
